### ISSUE TITLE
Cannot open saved model parameters for MUGEN

### ISSUE THREAD

**Issue by Crane-YU** [SongweiGe/TATS#12]
Hi @SongweiGe,

Thx for sharing this work. While I was looking into the code about text-video generation, the links you provided for downloading models parameters [VQGAN](https://www.dropbox.com/s/1fjfvapsre3jzjv/vqgan_mugen_256_41616_epoch%3D18-step%3D19999.ckpt?dl=1), [TATS-base](https://www.dropbox.com/s/45y44klhv04yzx8/coinrun_vqvae_lpips_gpt_16_256_41616_19999__epoch%3D59-step%3D379999-train.ckpt?dl=1) are not working.
Can u share the accessible links? Thx in advance.

**Comment by SongweiGe** [comment]
Hi Crane, thanks for pointing that out. It looks like the access has been changed to authorized people only. I'm not the owner of that files but I'm working on it!

**Comment by Crane-YU** [comment]
@SongweiGe thx for your effort. close this issue.

**Comment by SongweiGe** [comment]
Here are the checkpoints: https://drive.google.com/drive/folders/1uJ9cY2XhwBBC1vEYcg8G3BV_G-OJ5Ugn?usp=sharing. Let me know if you still cannot access them!

**Comment by KyonP** [comment]
> Here are the checkpoints: https://drive.google.com/drive/folders/1uJ9cY2XhwBBC1vEYcg8G3BV_G-OJ5Ugn?usp=sharing. Let me know if you still cannot access them!

is the link alive? I am trying to reproduce MUGEN results but seem like it is unavailable 😓
