### ISSUE TITLE
where to get 'i3d_pretrained_400.pt' & code for IS evaluation

### ISSUE THREAD

**Issue by wenyihong** [SongweiGe/TATS#13]
hi, great work!
1. where can we get 'i3d_pretrained_400.pt' for fvd evaluation?
2. can you provide with code for IS evaluation?
Thanks!

**Comment by SongweiGe** [comment]
Thank you for your interests! 

1. Please find the checkpoint here: https://github.com/SongweiGe/TATS/blob/main/tats/fvd/i3d_pretrained_400.pt

2. We generally saved the videos and computed IS using this repo offline: https://github.com/pfnet-research/tgan2. It is a chainer implementation but is quite simple to install. As an alternative, there is pytorch implementation here: https://github.com/universome/stylegan-v#evaluation. I haven't tried it myself, but the claim is that it is perfectly reproduced numbers.
