### ISSUE TITLE
What about the text-to-video generation performance if additional VQVAE is applied on text tokens?

### ISSUE THREAD

**Issue by Crane-YU** [SongweiGe/TATS#14]
Hi @SongweiGe, while reading the lines of [code](https://github.com/SongweiGe/TATS/blob/main/tats/tats_transformer.py#L92-L94) for encoding the text, I found identity layer is used to encode the text tokens, which already has been encoded by a tokenizer.
Just wondering whether the performance would be increased if additional VQVAE is to be applied on the encoded tokens? Have you done sort of experiments?

**Comment by SongweiGe** [comment]
We haven't done any experiments like you have suggested. I suspect that the current setting is probably enough for simple dataset with simple texts (auto-generated texts) like MUGEN. But for more complex dataset and real human language, either pretrained language model or specific trainable text encoder would certainly be necessary and boost the performance.
