### ISSUE TITLE
audio-video generation on custom dataset

### ISSUE THREAD

**Issue by realPasu** [SongweiGe/TATS#17]
Thank you so much for your excellent work!
I have a question about generating audio-guided videos on custom dataset. I noticed that a pre-trained VQGAN for audio encoding is required, but it seem that the script of training such a model is missed in the repo. Could you please share the script if it's convient to you?
Thank you again for your contribution to the community!

**Comment by SongweiGe** [comment]
Thank you for interests in our project. Please find the scripts below:
STFT VQVAE (note that GAN loss was not used to train this model):

```
python train_vqgan.py --embedding_dim 256 --n_codes 1024 --n_hiddens 32 --downsample 4 8 8 --no_random_restart \
                      --gpus 8 --sync_batchnorm --batch_size 6 --num_workers 32 --accumulate_grad_batches 2 \
                      --progress_bar_refresh_rate 500 --max_steps 2000000 --gradient_clip_val 1.0 --lr 3e-5 \
                      --data_path /checkpoint/songweig/data/AudioSet_Drums/drums/AudioSet_Dataset/stft \
                      --default_root_dir /checkpoint/songweig/ckpts/tatd/drum/vqgan_drum_stft \
                      --stft_data --sequence_length 16 --image_channels 1 --norm_type batch \
                      --perceptual_weight 4 --image_gan_weight 0 --video_gan_weight 0  --gan_feat_weight 0  
```

Video VQGAN:
```
python train_vqgan.py --embedding_dim 256 --n_codes 16384 --n_hiddens 32 --downsample 4 8 8 --no_random_restart \
                      --gpus 8 --sync_batchnorm --batch_size 6 --num_workers 32 --accumulate_grad_batches 2 \
                      --progress_bar_refresh_rate 500 --max_steps 2000000 --gradient_clip_val 1.0 --lr 3e-5 \
                      --data_path /checkpoint/songweig/data/AudioSet_Drums/drums/AudioSet_Dataset/video \
                      --default_root_dir /checkpoint/songweig/ckpts/tatd/drum/vqgan_drum_96_488 \
                      --resolution 96 --sequence_length 16 --discriminator_iter_start 10000 --norm_type batch \
                      --perceptual_weight 4 --image_gan_weight 1 --video_gan_weight 1  --gan_feat_weight 4 
```

Transformer:
```
python train_transformer.py --vqvae /checkpoint/songweig/ckpts/drum/vqgan_drum_96_488/lightning_logs/version_50876637/checkpoints/epoch=4-step=19999-10000-train/recon_loss=0.13.ckpt \
                        --stft_vqvae /checkpoint/songweig/ckpts/drum/vqgan_drum_stft/lightning_logs/version_50876621/checkpoints/epoch=1190-step=74999-train/recon_loss=0.29.ckpt \
                        --num_workers 32 --val_check_interval 0.5 --progress_bar_refresh_rate 1 \
                        --gpus 4 --sync_batchnorm --batch_size 2 --cond_stage_key stft\
                        --stft_data --data_path /fs/vulcan-projects/contrastive_learning_songweig/TATS/data/AudioSet_Dataset/stft \
                        --block_size 640 --n_layer 24 --n_head 16 --n_embd 1024  \
                        --default_root_dir /checkpoint/songweig/ckpts/drum/vqgan_stft_cond_gpt_drum_96_488_19999_749992 \
                        --resolution 96 --sequence_length 16 --max_steps 2000000 
```

**Comment by realPasu** [comment]
> Thank you for interests in our project. Please find the scripts below: STFT VQVAE (note that GAN loss was not used to train this model):
> 
> ```
> python train_vqgan.py --embedding_dim 256 --n_codes 1024 --n_hiddens 32 --downsample 4 8 8 --no_random_restart \
>                       --gpus 8 --sync_batchnorm --batch_size 6 --num_workers 32 --accumulate_grad_batches 2 \
>                       --progress_bar_refresh_rate 500 --max_steps 2000000 --gradient_clip_val 1.0 --lr 3e-5 \
>                       --data_path /checkpoint/songweig/data/AudioSet_Drums/drums/AudioSet_Dataset/stft \
>                       --default_root_dir /checkpoint/songweig/ckpts/tatd/drum/vqgan_drum_stft \
>                       --stft_data --sequence_length 16 --image_channels 1 --norm_type batch \
>                       --perceptual_weight 4 --image_gan_weight 0 --video_gan_weight 0  --gan_feat_weight 0  
> ```
> 
> Video VQGAN:
> 
> ```
> python train_vqgan.py --embedding_dim 256 --n_codes 16384 --n_hiddens 32 --downsample 4 8 8 --no_random_restart \
>                       --gpus 8 --sync_batchnorm --batch_size 6 --num_workers 32 --accumulate_grad_batches 2 \
>                       --progress_bar_refresh_rate 500 --max_steps 2000000 --gradient_clip_val 1.0 --lr 3e-5 \
>                       --data_path /checkpoint/songweig/data/AudioSet_Drums/drums/AudioSet_Dataset/video \
>                       --default_root_dir /checkpoint/songweig/ckpts/tatd/drum/vqgan_drum_96_488 \
>                       --resolution 96 --sequence_length 16 --discriminator_iter_start 10000 --norm_type batch \
>                       --perceptual_weight 4 --image_gan_weight 1 --video_gan_weight 1  --gan_feat_weight 4 
> ```
> 
> Transformer:
> 
> ```
> python train_transformer.py --vqvae /checkpoint/songweig/ckpts/drum/vqgan_drum_96_488/lightning_logs/version_50876637/checkpoints/epoch=4-step=19999-10000-train/recon_loss=0.13.ckpt \
>                         --stft_vqvae /checkpoint/songweig/ckpts/drum/vqgan_drum_stft/lightning_logs/version_50876621/checkpoints/epoch=1190-step=74999-train/recon_loss=0.29.ckpt \
>                         --num_workers 32 --val_check_interval 0.5 --progress_bar_refresh_rate 1 \
>                         --gpus 4 --sync_batchnorm --batch_size 2 --cond_stage_key stft\
>                         --stft_data --data_path /fs/vulcan-projects/contrastive_learning_songweig/TATS/data/AudioSet_Dataset/stft \
>                         --block_size 640 --n_layer 24 --n_head 16 --n_embd 1024  \
>                         --default_root_dir /checkpoint/songweig/ckpts/drum/vqgan_stft_cond_gpt_drum_96_488_19999_749992 \
>                         --resolution 96 --sequence_length 16 --max_steps 2000000 
> ```

Thank you so much for your detailed reply!

**Comment by realPasu** [comment]
> Thank you for interests in our project. Please find the scripts below: STFT VQVAE (note that GAN loss was not used to train this model):
> 
> ```
> python train_vqgan.py --embedding_dim 256 --n_codes 1024 --n_hiddens 32 --downsample 4 8 8 --no_random_restart \
>                       --gpus 8 --sync_batchnorm --batch_size 6 --num_workers 32 --accumulate_grad_batches 2 \
>                       --progress_bar_refresh_rate 500 --max_steps 2000000 --gradient_clip_val 1.0 --lr 3e-5 \
>                       --data_path /checkpoint/songweig/data/AudioSet_Drums/drums/AudioSet_Dataset/stft \
>                       --default_root_dir /checkpoint/songweig/ckpts/tatd/drum/vqgan_drum_stft \
>                       --stft_data --sequence_length 16 --image_channels 1 --norm_type batch \
>                       --perceptual_weight 4 --image_gan_weight 0 --video_gan_weight 0  --gan_feat_weight 0  
> ```
> 
> Video VQGAN:
> 
> ```
> python train_vqgan.py --embedding_dim 256 --n_codes 16384 --n_hiddens 32 --downsample 4 8 8 --no_random_restart \
>                       --gpus 8 --sync_batchnorm --batch_size 6 --num_workers 32 --accumulate_grad_batches 2 \
>                       --progress_bar_refresh_rate 500 --max_steps 2000000 --gradient_clip_val 1.0 --lr 3e-5 \
>                       --data_path /checkpoint/songweig/data/AudioSet_Drums/drums/AudioSet_Dataset/video \
>                       --default_root_dir /checkpoint/songweig/ckpts/tatd/drum/vqgan_drum_96_488 \
>                       --resolution 96 --sequence_length 16 --discriminator_iter_start 10000 --norm_type batch \
>                       --perceptual_weight 4 --image_gan_weight 1 --video_gan_weight 1  --gan_feat_weight 4 
> ```
> 
> Transformer:
> 
> ```
> python train_transformer.py --vqvae /checkpoint/songweig/ckpts/drum/vqgan_drum_96_488/lightning_logs/version_50876637/checkpoints/epoch=4-step=19999-10000-train/recon_loss=0.13.ckpt \
>                         --stft_vqvae /checkpoint/songweig/ckpts/drum/vqgan_drum_stft/lightning_logs/version_50876621/checkpoints/epoch=1190-step=74999-train/recon_loss=0.29.ckpt \
>                         --num_workers 32 --val_check_interval 0.5 --progress_bar_refresh_rate 1 \
>                         --gpus 4 --sync_batchnorm --batch_size 2 --cond_stage_key stft\
>                         --stft_data --data_path /fs/vulcan-projects/contrastive_learning_songweig/TATS/data/AudioSet_Dataset/stft \
>                         --block_size 640 --n_layer 24 --n_head 16 --n_embd 1024  \
>                         --default_root_dir /checkpoint/songweig/ckpts/drum/vqgan_stft_cond_gpt_drum_96_488_19999_749992 \
>                         --resolution 96 --sequence_length 16 --max_steps 2000000 
> ```

Thank you so much for your detailed reply!

**Comment by realPasu** [comment]
So sorry for further problems I met in experiments.
First, what shape should one stft file have? I tried both (t, 1 + nfft / 2) and (1 + nfft / 2, t), but no one of them works. I checked your code of StftDataset in "data.py", and found that there was an interpolation with output size (64, 16). It seems that only B*C*T*H shaped data can be interpolated like this. So could you please specify the shape of a stft file should have?
Second, it seems that the architecture of VQGAN in "tats_vqgan.py" only supports the input with shape B*C*T*H*W with multiple Conv3D, while the shape of stft data is seemingly B*1*T*H. Did I misunderstand anything? Or should I pre-process the stft data so that they can fit the network architecture?
Really looking forward to your reply!
Thank you again for your excellent work and contribution to the community!

**Comment by realPasu** [comment]
Besides, I found that there's a "TODO" flag at https://github.com/SongweiGe/TATS/blob/8ea1b587a74736d420b70cc2b52ac1683682ec6c/tats/tats_vqgan.py#L191 of stft data in "tats_vqgan.py". Whether the code of VQGAN for stft data is not implemented in the script? Or can I simply replace "x = batch['video']" by "x = batch['stft']" at the line for stft VQGAN at this line?

**Comment by SongweiGe** [comment]
Can you check the official data to compare with your own stft format? https://www.dropbox.com/s/7ykgybrc8nb3lgf/AudioSet_Drums.zip?dl=0

**Comment by realPasu** [comment]
> 

Thank you so much! I'll check it. Sorry to bother you~

**Comment by SongweiGe** [comment]
No problem. Feel free to let me know if you have more questions. : )

**Comment by suryadheeshjith** [comment]
I was wondering why you are using perceptual loss while you are training the STFT VQVAE.
