### ISSUE TITLE
On the Interpolation Transformer 

### ISSUE THREAD

**Issue by JHLew** [SongweiGe/TATS#19]
Hi, thanks for the awesome work.

I have been going through the codes to better understand the paper.
I wish to understand how the interpolation transformer is implemented, but could not find it.

I assume the transformer(GPT) of Net2NetTransformer of tats/tats_transformer.py is the autoregressive transformer, but there does not seem to be another transformer for interpolation?

I found the Casual Attention to be existent, but not the Interpolation Casual Attention.

Is it not provided or am I missing something? Could you kindly specify where to look?

**Comment by SongweiGe** [comment]
You should check the argument `n_unmasked `. For example, here:
https://github.com/SongweiGe/TATS/blob/8ea1b587a74736d420b70cc2b52ac1683682ec6c/tats/modules/gpt.py#L96

**Comment by SongweiGe** [comment]
That's correct!!
