### ISSUE TITLE
Unavailable MUGEN checkpoints

### ISSUE THREAD

**Issue by JustinYuu** [songweige/TATS#26]
Hi, the dropout link for the MUGEN checkpoint seems to be unavailable now. Could you please share another link? Thanks!

**Comment by songweige** [comment]
Hey Justin, thanks for pointing that out! Please find the updated links below!

- VQGAN: https://drive.google.com/file/d/1H-l80_zOYtIj2g7IonjRej00B9LeleRi/view?usp=sharing
- Transformer: https://drive.google.com/file/d/1uZICD3DgbRlto__mEEY6i0i9n20eRLcV/view?usp=sharing

Let me know if they work for you!

**Comment by JustinYuu** [comment]
Hi Songwei, thanks for your reply! The updated links are working now! They really help me a lot :)
