### ISSUE TITLE
Question on training the transformer

### ISSUE THREAD

**Issue by suryadheeshjith** [songweige/TATS#29]
Hello, I have a question regarding the training of the transformer. Would there be a leakage of ground truth information during the training of the transformer due to the receptive field of the 3D convolutions across time? The information contained in the last token's embedding might be present in other tokens preceding it. Would that cause inefficient learning of the token indices in the transformer?

**Comment by songweige** [comment]
Ummm, interesting. I don't know how much it affects the model training in practice if one restrictively constrains the respective field of the tokens to be non-overlapped. But I see your points here. It would be an interesting problem to look into!

**Comment by suryadheeshjith** [comment]
I read this from the Magvit paper (MAGVIT: Masked Generative Video Transformer) - "We argue that it is suboptimal to directly unmask the tokens corresponding to the region of the interior condition [12]. As discussed in Section 3.1, the non-local receptive field of the tokenizer can leak the ground-truth information into the unmasked tokens, leading to problematic non-causal masking and poor generalization."

This is why I thought there may be issues with masking the last token in TATS.

**Comment by suryadheeshjith** [comment]
Do you think a similar training procedure for Magvit would be helpful for autoregressive prediction?

**Comment by songweige** [comment]
I'm not exactly certain about what you mean by a similar training procedure, but the masking issue definitely sounds like a reasonable concern and can be improved on.

**Comment by suryadheeshjith** [comment]
Alright, thank you for your response!
