### ISSUE TITLE
Does the project support cuda11 and RTX3090?

### ISSUE THREAD

**Issue by yrcong** [SongweiGe/TATS#3]
Hi,

have you tried to train your model on a RTX30 GPU?

**Comment by SongweiGe** [comment]
Hi, @yrcong, thank you for your interests! We haven't tried to to train the model on a RTX30 gpu. But I did once use it with cuda11. I don't think there will be an issue that prevents the training on such gpus. You do need to choose the correct pytorch and pytorch-lightning versions. Feel free to let me know if you run into any issues!
