### ISSUE TITLE
Environment Setting

### ISSUE THREAD

**Issue by ludanruan** [SongweiGe/TATS#4]
In my setting, using conda to install pytorch and pip to install pytorch-lighting caused unmattchable problems and failed runing .

Here is my setting
```
  conda create -n tats python=3.8
  conda activate tats
  pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
  pip install pytorch-lightning
  pip install einops ftfy h5py imageio imageio-ffmpeg regex scikit-video tqdm av
```

but I still meet some warning as follows:
```
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (259, 259) to (272, 272) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0x6c83700] Warning: data is not aligned! This can lead to a speed loss
```
and
```
~/miniconda3/envs/tats/lib/python3.8/site-packages/torchvision/io/video.py:162: UserWarning: The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.
  warnings.warn("The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.")
```
Does this affect the final result?
Looking forward to your suggesstion and help。

**Comment by SongweiGe** [comment]
Hi, thank you for your interests in our work! For your first warning, I think it comes when you saved a video with `save_video_grid` function at https://github.com/SongweiGe/TATS/blob/9df70e86b3c279e7c0e4f477ebd8f61153221264/tats/utils.py#L134. I ran into similar warnings before and I don't think it should affect anything.

For your second warning, I think it appears as a result of a upgraded version of torchvision, which I haven't seen before. But in general, I don't think either of these two issues should affect running. What error messages did you see exactly that caused the failure?
