### ISSUE TITLE
Checkpoints of the interpolation Transformer and how to use it for inference?

### ISSUE THREAD

**Issue by llyx97** [SongweiGe/TATS#8]
Hi, thanks for the great work and the released codes! I'm very interested in it.
Could you release the checkpoints of the interpolation Transformer and provide instructions on how to use them for inference? (which seems not provided in the current repository)

**Comment by SongweiGe** [comment]
Hi llyx97, thank you for your interests in our work. Please find the instructions as well as the updated checkpoints and inference code with the hierarchical models under the synthesis section: https://github.com/SongweiGe/TATS#synthesis.

**Comment by llyx97** [comment]
Great. Thanks for the response and timely update!
